"""Push a scraped JSONL file to HuggingFace as a Dataset.

Reads {output_dir}/{name}.jsonl, converts to a datasets.Dataset,
and pushes to TigreGotico/media-metadata-{name} (or --repo override).

Usage:
    python scrapers/push_to_hub.py --name tvmaze_shows [options]

Options:
    --name NAME        Scraper name (matches JSONL filename stem)
    --output DIR       Directory containing the JSONL (default: ~/.cache/metadatarr/scrapers)
    --repo REPO        HuggingFace repo id (default: TigreGotico/media-metadata-{name})
    --private          Create/keep the dataset private (default: private)
    --public           Make the dataset public
    --token TOKEN      HF token (default: reads HF_TOKEN env or huggingface-cli login)
    --dry-run          Parse + validate but don't push

Requirements:
    pip install datasets huggingface_hub
    (or: pip install metadatarr[scrapers])
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

from metadatarr.scrapers._checkpoint import count_rows, default_output_dir

# Lazy imports so the module can be inspected without datasets installed
_datasets = None
_hf_hub = None


def _import_deps() -> None:
    global _datasets, _hf_hub
    try:
        import datasets as _d
        _datasets = _d
    except ImportError:
        raise ImportError(
            "push_to_hub requires the 'datasets' package.\n"
            "Install with: pip install datasets huggingface_hub\n"
            "or: pip install 'metadatarr[scrapers]'"
        )
    try:
        import huggingface_hub as _h
        _hf_hub = _h
    except ImportError:
        raise ImportError(
            "push_to_hub requires the 'huggingface_hub' package.\n"
            "Install with: pip install huggingface_hub"
        )


def _coerce_row(row: Dict[str, Any]) -> Dict[str, Any]:
    """Ensure type consistency across rows (mixed int/str in year/id fields, etc.)."""
    _YEAR_FIELDS = {"year", "start_year", "end_year", "inception_year",
                    "dissolved_year", "copyright_year", "first_publish_year"}
    _STR_ID_FIELDS = {"soundcloud_id", "bandcamp_id", "user_id", "band_id",
                      "adb_id", "ma_id", "mb_id", "wikidata_id"}
    for k, v in row.items():
        if v is None:
            continue
        if k.endswith("_year") or k in _YEAR_FIELDS:
            try:
                row[k] = int(v)
            except (ValueError, TypeError):
                row[k] = None
        elif k in _STR_ID_FIELDS or k.endswith("_id"):
            row[k] = str(v)
    return row


def _read_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                try:
                    rows.append(_coerce_row(json.loads(line)))
                except json.JSONDecodeError:
                    continue
    return rows


def _make_dataset_card(name: str, repo_id: str, n_rows: int, sample: Dict[str, Any]) -> str:
    fields = "\n".join(f"- `{k}`" for k in sample.keys())
    is_drug = "drugs-and-substances" in repo_id
    collection_tag = "drugs-and-substances" if is_drug else "media-metadata"
    collection_url = (
        "https://huggingface.co/collections/LeData/drugs-and-substances"
        if is_drug else
        "https://huggingface.co/collections/LeData/media-metadata"
    )
    return f"""---
license: cc0-1.0
tags:
  - {collection_tag}
  - entity-dataset
---

# {repo_id}

Rich entity dataset scraped by [metadatarr](https://github.com/TigreGotico/metadatarr)
scraper `{name}`.

Part of the [{collection_tag}]({collection_url}) collection.

**Rows**: {n_rows:,}

## Fields

{fields}

## Source

Generated by `scrapers/{name}.py`. See the metadatarr repo for the full
pipeline and scraper source code.
"""


def push(
    name: str,
    output_dir: Path,
    repo_id: str,
    private: bool,
    token: Optional[str],
    dry_run: bool,
) -> None:
    _import_deps()

    jsonl_path = output_dir / f"{name}.jsonl"
    if not jsonl_path.exists():
        raise FileNotFoundError(f"No JSONL file found at {jsonl_path}")

    n_rows = count_rows(name, output_dir)
    print(f"Loading {n_rows:,} rows from {jsonl_path} …", flush=True)

    # Stream via generator — avoids loading all rows into RAM and lets us
    # infer schema from a representative sample before committing to arrow types.
    def _gen():
        with open(jsonl_path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    try:
                        yield _coerce_row(json.loads(line))
                    except Exception:
                        continue

    # Sample first 2000 rows to detect mixed-type columns, then cast all such
    # columns to string so PyArrow doesn't infer int64 then choke on str later.
    sample = []
    col_has_str: set = set()
    col_has_int: set = set()
    col_has_list: set = set()
    col_has_scalar: set = set()

    def _scan_row(r: dict) -> None:
        for k, v in r.items():
            if isinstance(v, list):
                col_has_list.add(k)
            else:
                if isinstance(v, int):
                    col_has_int.add(k)
                if isinstance(v, str):
                    col_has_str.add(k)
                if v is not None:
                    col_has_scalar.add(k)

    with open(jsonl_path, encoding="utf-8") as fh:
        for i, line in enumerate(fh):
            if i >= 2000:
                break
            if not line.strip():
                continue
            try:
                r = _coerce_row(json.loads(line))
            except Exception:
                continue
            sample.append(r)
            _scan_row(r)

    if not sample:
        raise ValueError("JSONL is empty, nothing to push.")

    mixed_cols = col_has_str & col_has_int
    # Columns that are lists in some rows but scalars in others: wrap scalars in []
    list_or_scalar_cols = col_has_list & col_has_scalar

    # Collect full key universe from sample so every yielded row has the same keys.
    all_keys: set = set()
    for r in sample:
        all_keys.update(r.keys())
    # Scan tail + middle windows to catch sparse/late columns and type mismatches.
    with open(jsonl_path, encoding="utf-8") as fh:
        lines = fh.readlines()
    total_lines = len(lines)
    mid_start = max(2000, total_lines // 2 - 1000)
    for line in lines[-2000:] + lines[mid_start:mid_start + 2000]:
        line = line.strip()
        if not line:
            continue
        try:
            r2 = json.loads(line)
            all_keys.update(r2.keys())
            _scan_row(r2)
        except Exception:
            continue
    del lines

    # Re-evaluate after all scans
    mixed_cols = col_has_str & col_has_int
    # Any column ever seen as a list must always emit a list.
    always_list_cols = col_has_list
    # Columns that were always None in every sample window: Arrow infers them as
    # null type; any actual value later breaks the cast.  Force to str.
    col_with_data = col_has_str | col_has_int | col_has_list
    null_cols = all_keys - col_with_data

    def _gen_safe():
        with open(jsonl_path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    r = _coerce_row(json.loads(line))
                except Exception:
                    continue
                for col in mixed_cols:
                    if col in r and r[col] is not None:
                        r[col] = str(r[col])
                for col in always_list_cols:
                    if col in r and not isinstance(r[col], list):
                        r[col] = [r[col]] if r[col] is not None else []
                # Columns that were all-None in sample windows: force to str to
                # prevent Arrow inferring null type and then failing on real values.
                for col in null_cols:
                    if col in r and r[col] is not None:
                        r[col] = str(r[col])
                # Fill missing keys with None so every row has identical schema
                for k in all_keys:
                    if k not in r:
                        r[k] = None
                yield r

    print(f"  Streaming rows (mixed-type cols: str/int={sorted(mixed_cols)}, always-list={sorted(always_list_cols)}) …", flush=True)

    # Build explicit features to avoid Arrow inferring null type for sparse columns.
    import pyarrow as _pa
    _feat_map = {}
    for k in all_keys:
        if k in always_list_cols:
            _feat_map[k] = _datasets.Sequence(_datasets.Value("string"))
        elif k in (col_has_str | null_cols):
            _feat_map[k] = _datasets.Value("string")
        elif k in col_has_int and k not in mixed_cols:
            _feat_map[k] = _datasets.Value("int64")
        else:
            _feat_map[k] = _datasets.Value("string")
    features = _datasets.Features(_feat_map)

    dataset = _datasets.Dataset.from_generator(_gen_safe, features=features)
    print(f"  Dataset schema: {dataset.features}", flush=True)

    if dry_run:
        print("--dry-run: skipping push.", flush=True)
        return

    card_content = _make_dataset_card(name, repo_id, n_rows, sample[0])

    print(f"Pushing to {repo_id} (private={private}) …", flush=True)
    dataset.push_to_hub(
        repo_id,
        private=private,
        token=token,
        commit_message=f"scrapers/{name}: {n_rows:,} rows",
    )

    # Upload dataset card
    _hf_hub.upload_file(
        path_or_fileobj=card_content.encode(),
        path_in_repo="README.md",
        repo_id=repo_id,
        repo_type="dataset",
        token=token,
        commit_message="Add dataset card",
    )

    print(f"Done. Dataset available at https://huggingface.co/datasets/{repo_id}", flush=True)


def main() -> None:
    ap = argparse.ArgumentParser(description="Push scraped JSONL to HuggingFace Datasets")
    ap.add_argument("--name", required=True, help="Scraper name (JSONL stem)")
    ap.add_argument("--output", default=str(default_output_dir()))
    ap.add_argument("--repo", default=None, help="HF repo id (default: TigreGotico/media-metadata-{name})")
    ap.add_argument("--private", dest="private", action="store_true", default=True)
    ap.add_argument("--public", dest="private", action="store_false")
    ap.add_argument("--token", default=os.environ.get("HF_TOKEN"))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    output_dir = Path(args.output)
    if args.repo:
        repo_id = args.repo
    elif args.name.endswith("_drugs") or args.name.startswith("drugs_") or args.name in (
        "unified_drugs", "cmu_pronunciations", "wiktionary_pronunciations",
    ):
        repo_id = f"LeData/drugs-and-substances-{args.name.replace('_', '-').removesuffix('-drugs')}"
    else:
        repo_id = f"LeData/media-metadata-{args.name.replace('_', '-')}"

    push(
        name=args.name,
        output_dir=output_dir,
        repo_id=repo_id,
        private=args.private,
        token=args.token,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    main()
